Move asdf-vm install into seperate file

diff --git a/scripts/install-dotfiles b/scripts/install-dotfiles
--- a/scripts/install-dotfiles
+++ b/scripts/install-dotfiles
@@ -2,25 +2,12 @@
 # Download dotfiles and corresponding plugin managers
 # credits: https://www.atlassian.com/git/tutorials/dotfiles
 
-DOTFILES_REPO="${1:-https://github.com/coma64/dotfiles}"
-DOTFILES_BRANCH="${2:-master}"
+source './util.bash'
+
+DOTFILES_REPO="${DOTFILES_REPO:-https://github.com/coma64/dotfiles}"
+DOTFILES_BRANCH="${DOTFILES_BRANCH:-master}"
 DOTFILES_DIRECTORY="${DOTFILES_DIRECTORY:-${HOME}/.local/share/dotfiles}"
 DOTFILES_BACKUP_DIRECTORY="${DOTFILES_BACKUP_DIRECTORY:-${HOME}/.config-backup}"
-
-# zinit - zsh plugin manager
-sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
-# dein - vim plugin manager
-curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh \
-    | sh -s '/home/coma/.local/share/dein'
-# tpm - tmux plugin manager
-git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
-
-# My dotfiles
-git clone --bare "${DOTFILES_REPO}" "${DOTFILES_DIRECTORY}"
-
-err() {
-  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
-}
 
 config() {
     git --git-dir="${DOTFILES_DIRECTORY}" --work-tree="${HOME}" "$@"
@@ -30,6 +17,19 @@ backup_file() {
     mkdir --parents "$(dirname "${DOTFILES_BACKUP_DIRECTORY}/$1")"
     mv "$1" "${DOTFILES_BACKUP_DIRECTORY}/$1"
 }
+
+cd "${HOME}" || abort "Can't cd into home directory."
+
+# zinit - zsh plugin manager
+sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
+# dein - vim plugin manager
+curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh \
+    | sh -s "${HOME}/.local/share/dein"
+# tpm - tmux plugin manager
+git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+
+# My dotfiles
+git clone --bare "${DOTFILES_REPO}" "${DOTFILES_DIRECTORY}"
 
 if config checkout "${DOTFILES_BRANCH}"; then
     echo 'Checked out config.';
@@ -41,7 +41,7 @@ else
     export -f backup_file
     export DOTFILES_BACKUP_DIRECTORY
     config checkout "${DOTFILES_BRANCH}" 2>&1 \
-        | egrep '\s+\.' \
+        | grep -E '\s+\.' \
         | awk '{ print $1 }' \
         | xargs -I '{}' bash -c "backup_file '{}' && echo 'Backing up {}'"
 fi
@@ -49,5 +49,5 @@ fi
 if config checkout "${DOTFILES_BRANCH}"; then
     config config status.showUntrackedFiles no
 else
-    err 'Failed installing dotfiles'
+    abort "Failed checking out dotfiles"
 fi
